# fly.toml app configuration file generated for findservers on 2025-06-02T20:21:18-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'findservers'
primary_region = 'atl'

[build]
[build.args]
GO_VERSION = '1.24.3'

[env]
PORT = '8080'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'off'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
