package api

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strconv"

	"findservers/models"
)

func GetSampleServers(w http.ResponseWriter, r *http.Request) {
	// Get count from query parameter, default to 50
	countStr := r.URL.Query().Get("count")
	count := 50
	if countStr != "" {
		if parsedCount, err := strconv.Atoi(countStr); err == nil && parsedCount > 0 {
			count = parsedCount
		}
	}

	servers := generateSampleServers(count)

	jsonBytes, err := json.Marshal(servers)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.Write(jsonBytes)
}

func generateSampleServers(count int) []models.Server {
	// Define sample server templates
	sampleServers := []models.Server{
		{
			Addr:       "192.168.1.100:27015",
			GamePort:   27015,
			Name:       "[FACEIT] EU Central #1",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     3, // EU
			Players:    8,
			MaxPlayers: 10,
			Bots:       0,
			Map:        "de_dust2",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "competitive,128tick",
		},
		{
			Addr:       "74.91.112.45:27015",
			GamePort:   27015,
			Name:       "ESEA | Chicago #5",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     0, // US
			Players:    10,
			MaxPlayers: 10,
			Bots:       0,
			Map:        "de_mirage",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "scrim,128tick",
		},
		{
			Addr:       "185.25.205.12:27015",
			GamePort:   27015,
			Name:       "Community Retakes | EU West",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     3, // EU
			Players:    15,
			MaxPlayers: 16,
			Bots:       1,
			Map:        "de_inferno",
			Secure:     false,
			Dedicated:  true,
			OS:         "l",
			GameType:   "retakes,community",
		},
		{
			Addr:       "208.167.238.85:27015",
			GamePort:   27015,
			Name:       "West Coast DM | 24/7 Dust2",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     1, // US West
			Players:    0,
			MaxPlayers: 32,
			Bots:       5,
			Map:        "de_dust2",
			Secure:     true,
			Dedicated:  true,
			OS:         "w",
			GameType:   "deathmatch,24/7",
		},
		{
			Addr:       "192.168.1.100:27015",
			GamePort:   27015,
			Name:       "[FACEIT] EU Central #1",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     3, // EU
			Players:    8,
			MaxPlayers: 10,
			Bots:       0,
			Map:        "de_dust2",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "competitive,128tick",
		},
		{
			Addr:       "74.91.112.45:27015",
			GamePort:   27015,
			Name:       "ESEA | Chicago #5",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     0, // US
			Players:    10,
			MaxPlayers: 10,
			Bots:       0,
			Map:        "de_mirage",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "scrim,128tick",
		},
		{
			Addr:       "185.25.205.12:27015",
			GamePort:   27015,
			Name:       "Community Retakes | EU West",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     3, // EU
			Players:    15,
			MaxPlayers: 16,
			Bots:       1,
			Map:        "de_inferno",
			Secure:     false,
			Dedicated:  true,
			OS:         "l",
			GameType:   "retakes,community",
		},
		{
			Addr:       "208.167.238.85:27015",
			GamePort:   27015,
			Name:       "West Coast DM | 24/7 Dust2",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     1, // US West
			Players:    0,
			MaxPlayers: 32,
			Bots:       5,
			Map:        "de_dust2",
			Secure:     true,
			Dedicated:  true,
			OS:         "w",
			GameType:   "deathmatch,24/7",
		},
		{
			Addr:       "87.98.145.22:27015",
			GamePort:   27015,
			Name:       "[FACEIT] EU West #3",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     3, // EU
			Players:    6,
			MaxPlayers: 10,
			Bots:       0,
			Map:        "de_cache",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "competitive,128tick",
		},
		{
			Addr:       "103.28.54.171:27015",
			GamePort:   27015,
			Name:       "Singapore MM | Casual",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     5, // Asia
			Players:    12,
			MaxPlayers: 20,
			Bots:       2,
			Map:        "de_mirage",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "casual,64tick",
		},
		{
			Addr:       "162.248.92.15:27015",
			GamePort:   27015,
			Name:       "NYC Competitive #12",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     0, // US
			Players:    4,
			MaxPlayers: 10,
			Bots:       0,
			Map:        "de_overpass",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "competitive,128tick",
		},
		{
			Addr:       "51.77.203.94:27015",
			GamePort:   27015,
			Name:       "UK Retakes Server",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     3, // EU
			Players:    8,
			MaxPlayers: 12,
			Bots:       0,
			Map:        "de_train",
			Secure:     false,
			Dedicated:  true,
			OS:         "l",
			GameType:   "retakes,community",
		},
		{
			Addr:       "139.180.140.33:27015",
			GamePort:   27015,
			Name:       "Tokyo Community Server",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     5, // Asia
			Players:    18,
			MaxPlayers: 20,
			Bots:       0,
			Map:        "de_dust2",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "casual,community",
		},
		{
			Addr:       "198.51.100.44:27015",
			GamePort:   27015,
			Name:       "Dallas DM Aim Map",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     0, // US
			Players:    15,
			MaxPlayers: 24,
			Bots:       0,
			Map:        "aim_map",
			Secure:     true,
			Dedicated:  true,
			OS:         "w",
			GameType:   "deathmatch,aim",
		},
		{
			Addr:       "45.76.142.88:27015",
			GamePort:   27015,
			Name:       "Sydney Surf Server",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     6, // Australia
			Players:    7,
			MaxPlayers: 32,
			Bots:       0,
			Map:        "surf_ski_2",
			Secure:     false,
			Dedicated:  true,
			OS:         "l",
			GameType:   "surf,community",
		},
		{
			Addr:       "37.230.114.56:27015",
			GamePort:   27015,
			Name:       "German Knife Round",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     3, // EU
			Players:    3,
			MaxPlayers: 16,
			Bots:       1,
			Map:        "de_nuke",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "knife,community",
		},
		{
			Addr:       "104.238.130.77:27015",
			GamePort:   27015,
			Name:       "LA Jailbreak #2",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     1, // US West
			Players:    22,
			MaxPlayers: 32,
			Bots:       0,
			Map:        "jb_summer",
			Secure:     false,
			Dedicated:  true,
			OS:         "l",
			GameType:   "jailbreak,community",
		},
		{
			Addr:       "116.202.57.91:27015",
			GamePort:   27015,
			Name:       "[ESEA] EU North #8",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     3, // EU
			Players:    10,
			MaxPlayers: 10,
			Bots:       0,
			Map:        "de_ancient",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "scrim,128tick",
		},
		{
			Addr:       "172.96.162.33:27015",
			GamePort:   27015,
			Name:       "Miami Beach Casual",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     0, // US
			Players:    16,
			MaxPlayers: 20,
			Bots:       3,
			Map:        "de_vertigo",
			Secure:     true,
			Dedicated:  true,
			OS:         "w",
			GameType:   "casual,64tick",
		},
		{
			Addr:       "141.95.98.42:27015",
			GamePort:   27015,
			Name:       "Paris Competitive Hub",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     3, // EU
			Players:    2,
			MaxPlayers: 10,
			Bots:       0,
			Map:        "de_mirage",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "competitive,128tick",
		},
		{
			Addr:       "27.50.94.155:27015",
			GamePort:   27015,
			Name:       "Hong Kong DM Server",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     5, // Asia
			Players:    11,
			MaxPlayers: 24,
			Bots:       2,
			Map:        "de_dust2",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "deathmatch,community",
		},
		{
			Addr:       "89.163.142.67:27015",
			GamePort:   27015,
			Name:       "Stockholm Retakes Pro",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     3, // EU
			Players:    9,
			MaxPlayers: 16,
			Bots:       0,
			Map:        "de_cache",
			Secure:     false,
			Dedicated:  true,
			OS:         "l",
			GameType:   "retakes,128tick",
		},
		{
			Addr:       "206.189.85.23:27015",
			GamePort:   27015,
			Name:       "Toronto Mixed Server",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     0, // US
			Players:    14,
			MaxPlayers: 18,
			Bots:       1,
			Map:        "de_inferno",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "casual,mixed",
		},
		{
			Addr:       "213.32.7.119:27015",
			GamePort:   27015,
			Name:       "Moscow Elite Gaming",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     4, // Russia
			Players:    5,
			MaxPlayers: 10,
			Bots:       0,
			Map:        "de_overpass",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "competitive,128tick",
		},
		{
			Addr:       "158.69.23.144:27015",
			GamePort:   27015,
			Name:       "Montreal KZ Climbing",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     0, // US
			Players:    6,
			MaxPlayers: 32,
			Bots:       0,
			Map:        "kz_longjumps2",
			Secure:     false,
			Dedicated:  true,
			OS:         "l",
			GameType:   "kreedz,community",
		},
		{
			Addr:       "103.107.198.25:27015",
			GamePort:   27015,
			Name:       "Mumbai Casual Play",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     5, // Asia
			Players:    8,
			MaxPlayers: 20,
			Bots:       4,
			Map:        "de_dust2",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "casual,64tick",
		},
		{
			Addr:       "195.154.200.31:27015",
			GamePort:   27015,
			Name:       "Netherlands Pro Scrim",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     3, // EU
			Players:    8,
			MaxPlayers: 10,
			Bots:       0,
			Map:        "de_train",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "scrim,128tick",
		},
		{
			Addr:       "144.217.163.88:27015",
			GamePort:   27015,
			Name:       "Vancouver Wingman",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     1, // US West
			Players:    2,
			MaxPlayers: 4,
			Bots:       0,
			Map:        "de_shortdust",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "wingman,128tick",
		},
		{
			Addr:       "128.199.44.67:27015",
			GamePort:   27015,
			Name:       "Seoul Gaming Hub",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     5, // Asia
			Players:    13,
			MaxPlayers: 16,
			Bots:       0,
			Map:        "de_mirage",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "competitive,community",
		},
		{
			Addr:       "78.141.207.52:27015",
			GamePort:   27015,
			Name:       "Italian Aim Training",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     3, // EU
			Players:    4,
			MaxPlayers: 16,
			Bots:       0,
			Map:        "aim_redline",
			Secure:     false,
			Dedicated:  true,
			OS:         "l",
			GameType:   "aim,training",
		},
		{
			Addr:       "67.207.67.3:27015",
			GamePort:   27015,
			Name:       "Boston University League",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     0, // US
			Players:    10,
			MaxPlayers: 10,
			Bots:       0,
			Map:        "de_ancient",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "league,128tick",
		},
		{
			Addr:       "159.69.208.144:27015",
			GamePort:   27015,
			Name:       "Berlin Surf Paradise",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     3, // EU
			Players:    12,
			MaxPlayers: 32,
			Bots:       0,
			Map:        "surf_mesa",
			Secure:     false,
			Dedicated:  true,
			OS:         "l",
			GameType:   "surf,community",
		},
		{
			Addr:       "138.197.148.92:27015",
			GamePort:   27015,
			Name:       "Atlanta Gun Game",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     0, // US
			Players:    8,
			MaxPlayers: 16,
			Bots:       0,
			Map:        "gg_simpsons",
			Secure:     true,
			Dedicated:  true,
			OS:         "w",
			GameType:   "gungame,community",
		},
		{
			Addr:       "80.240.16.78:27015",
			GamePort:   27015,
			Name:       "Prague Elite Match",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     3, // EU
			Players:    6,
			MaxPlayers: 10,
			Bots:       0,
			Map:        "de_vertigo",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "competitive,128tick",
		},
		{
			Addr:       "170.64.189.123:27015",
			GamePort:   27015,
			Name:       "Phoenix Retakes Only",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     1, // US West
			Players:    11,
			MaxPlayers: 16,
			Bots:       1,
			Map:        "de_nuke",
			Secure:     false,
			Dedicated:  true,
			OS:         "l",
			GameType:   "retakes,community",
		},
		{
			Addr:       "45.32.155.99:27015",
			GamePort:   27015,
			Name:       "Melbourne Competitive",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     6, // Australia
			Players:    4,
			MaxPlayers: 10,
			Bots:       0,
			Map:        "de_inferno",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "competitive,128tick",
		},
		{
			Addr:       "91.134.232.167:27015",
			GamePort:   27015,
			Name:       "Spain Gaming Central",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     3, // EU
			Players:    17,
			MaxPlayers: 20,
			Bots:       2,
			Map:        "de_dust2",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "casual,community",
		},
		{
			Addr:       "165.227.99.45:27015",
			GamePort:   27015,
			Name:       "Chicago Bhop Server",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     0, // US
			Players:    3,
			MaxPlayers: 32,
			Bots:       0,
			Map:        "bhop_badges",
			Secure:     false,
			Dedicated:  true,
			OS:         "l",
			GameType:   "bhop,community",
		},
		{
			Addr:       "51.195.102.33:27015",
			GamePort:   27015,
			Name:       "Warsaw Knife Arena",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     3, // EU
			Players:    6,
			MaxPlayers: 12,
			Bots:       0,
			Map:        "de_cache",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "knife,community",
		},
		{
			Addr:       "142.44.242.56:27015",
			GamePort:   27015,
			Name:       "Seattle Pro Practice",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     1, // US West
			Players:    10,
			MaxPlayers: 10,
			Bots:       0,
			Map:        "de_mirage",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "scrim,128tick",
		},
		{
			Addr:       "103.68.62.89:27015",
			GamePort:   27015,
			Name:       "Bangkok Casual Mix",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     5, // Asia
			Players:    14,
			MaxPlayers: 20,
			Bots:       3,
			Map:        "de_overpass",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "casual,64tick",
		},
		{
			Addr:       "188.165.200.77:27015",
			GamePort:   27015,
			Name:       "Vienna Headshot Only",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     3, // EU
			Players:    9,
			MaxPlayers: 24,
			Bots:       0,
			Map:        "de_dust2",
			Secure:     false,
			Dedicated:  true,
			OS:         "l",
			GameType:   "headshot,community",
		},
		{
			Addr:       "68.183.201.22:27015",
			GamePort:   27015,
			Name:       "Austin 1v1 Arena",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     0, // US
			Players:    2,
			MaxPlayers: 16,
			Bots:       0,
			Map:        "aim_dust2_long",
			Secure:     true,
			Dedicated:  true,
			OS:         "w",
			GameType:   "1v1,arena",
		},
		{
			Addr:       "95.216.24.133:27015",
			GamePort:   27015,
			Name:       "Helsinki Nordic Pro",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     3, // EU
			Players:    8,
			MaxPlayers: 10,
			Bots:       0,
			Map:        "de_ancient",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "competitive,128tick",
		},
		{
			Addr:       "146.56.173.55:27015",
			GamePort:   27015,
			Name:       "Auckland Gaming Hub",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     6, // Australia
			Players:    15,
			MaxPlayers: 20,
			Bots:       1,
			Map:        "de_train",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "casual,community",
		},
		{
			Addr:       "167.114.158.99:27015",
			GamePort:   27015,
			Name:       "Quebec Zombie Escape",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     0, // US
			Players:    28,
			MaxPlayers: 32,
			Bots:       0,
			Map:        "ze_santassination",
			Secure:     false,
			Dedicated:  true,
			OS:         "l",
			GameType:   "zombie,community",
		},
		{
			Addr:       "5.189.143.177:27015",
			GamePort:   27015,
			Name:       "Brussels Weapon Course",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     3, // EU
			Players:    7,
			MaxPlayers: 16,
			Bots:       2,
			Map:        "training1",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "training,aim",
		},
		{
			Addr:       "198.199.86.11:27015",
			GamePort:   27015,
			Name:       "Las Vegas High Stakes",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     1, // US West
			Players:    6,
			MaxPlayers: 10,
			Bots:       0,
			Map:        "de_vertigo",
			Secure:     true,
			Dedicated:  true,
			OS:         "w",
			GameType:   "competitive,128tick",
		},
		{
			Addr:       "45.77.34.88:27015",
			GamePort:   27015,
			Name:       "Singapore Surf Elite",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     5, // Asia
			Players:    19,
			MaxPlayers: 32,
			Bots:       0,
			Map:        "surf_greatriver",
			Secure:     false,
			Dedicated:  true,
			OS:         "l",
			GameType:   "surf,community",
		},
		{
			Addr:       "149.202.89.166:27015",
			GamePort:   27015,
			Name:       "Lyon French Connection",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     3, // EU
			Players:    12,
			MaxPlayers: 16,
			Bots:       1,
			Map:        "de_nuke",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "retakes,community",
		},
		{
			Addr:       "192.81.210.44:27015",
			GamePort:   27015,
			Name:       "Detroit Motor City DM",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     0, // US
			Players:    20,
			MaxPlayers: 32,
			Bots:       4,
			Map:        "de_dust2",
			Secure:     true,
			Dedicated:  true,
			OS:         "w",
			GameType:   "deathmatch,24/7",
		},
		{
			Addr:       "185.107.96.211:27015",
			GamePort:   27015,
			Name:       "Oslo Norwegian Elite",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     3, // EU
			Players:    4,
			MaxPlayers: 10,
			Bots:       0,
			Map:        "de_inferno",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "competitive,128tick",
		},
		{
			Addr:       "104.156.230.77:27015",
			GamePort:   27015,
			Name:       "Portland Pacific NW",
			AppID:      730,
			GameDir:    "csgo",
			Version:    "1.38.8.5",
			Product:    "csgo",
			Region:     1, // US West
			Players:    16,
			MaxPlayers: 18,
			Bots:       0,
			Map:        "de_cache",
			Secure:     true,
			Dedicated:  true,
			OS:         "l",
			GameType:   "casual,community",
		},
	}

	var result []models.Server

	for i := range count {
		// Cycle through sample servers
		baseServer := sampleServers[i%len(sampleServers)]

		// Create a copy and modify it slightly to make it unique
		server := baseServer
		server.Addr = fmt.Sprintf("%s:%d", generateIP(i), 27015+i%10)

		// Vary player counts
		if i%5 == 0 {
			server.Players = 0
		} else if i%3 == 0 {
			server.Players = server.MaxPlayers // Full server
		} else {
			server.Players = (i % server.MaxPlayers) + 1
		}

		result = append(result, server)
	}

	return result
}

func generateIP(seed int) string {
	// Generate semi-realistic IP addresses
	ips := []string{
		"192.168.1.%d",
		"74.91.112.%d",
		"185.25.205.%d",
		"208.167.238.%d",
		"104.153.106.%d",
	}

	return fmt.Sprintf(ips[seed%len(ips)], (seed%200)+50)
}
